// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package model

import (
	"time"
)

const (
	KeycloakScopes = "keycloak.Scopes"
)

// Defines values for ReceiptStatus.
const (
	Accepted    ReceiptStatus = "accepted"
	Declined    ReceiptStatus = "declined"
	Submitted   ReceiptStatus = "submitted"
	Unsubmitted ReceiptStatus = "unsubmitted"
)

// Valid indicates whether the value is a known member of the ReceiptStatus enum.
func (e ReceiptStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Declined:
		return true
	case Submitted:
		return true
	case Unsubmitted:
		return true
	default:
		return false
	}
}

// Defines values for RoomType.
const (
	ClassRoom              RoomType = "ClassRoom"
	ComputerRoom           RoomType = "ComputerRoom"
	FacilityManagementRoom RoomType = "FacilityManagementRoom"
	Kindergarden           RoomType = "Kindergarden"
	Library                RoomType = "Library"
	MeetingRoom            RoomType = "MeetingRoom"
	Music                  RoomType = "Music"
	SchoolManagementRoom   RoomType = "SchoolManagementRoom"
	SchoolSecretariatRoom  RoomType = "SchoolSecretariatRoom"
	ScienceRoom            RoomType = "ScienceRoom"
	TeacherRoom            RoomType = "TeacherRoom"
	Theater                RoomType = "Theater"
	Video                  RoomType = "Video"
)

// Valid indicates whether the value is a known member of the RoomType enum.
func (e RoomType) Valid() bool {
	switch e {
	case ClassRoom:
		return true
	case ComputerRoom:
		return true
	case FacilityManagementRoom:
		return true
	case Kindergarden:
		return true
	case Library:
		return true
	case MeetingRoom:
		return true
	case Music:
		return true
	case SchoolManagementRoom:
		return true
	case SchoolSecretariatRoom:
		return true
	case ScienceRoom:
		return true
	case TeacherRoom:
		return true
	case Theater:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Address defines model for Address.
type Address struct {
	ID         string      `json:"id"`
	Number     *string     `json:"number,omitempty"`
	PostalCode *PostalCode `json:"postalCode,omitempty"`
	Street     *string     `json:"street,omitempty"`
	Version    int         `json:"version"`
}

// AddressRequest defines model for AddressRequest.
type AddressRequest struct {
	Number     *string        `json:"number,omitempty"`
	PostalCode *PostalCodeRef `json:"postalCode,omitempty"`
	Street     *string        `json:"street,omitempty"`
	Version    int            `json:"version"`
}

// Building defines model for Building.
type Building struct {
	ID       string    `json:"id"`
	Location *Location `json:"location,omitempty"`
	Name     string    `json:"name"`
	Version  int       `json:"version"`
}

// BuildingRequest defines model for BuildingRequest.
type BuildingRequest struct {
	Location *EntityRef `json:"location,omitempty"`
	Name     string     `json:"name"`
	Version  int        `json:"version"`
}

// City defines model for City.
type City struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	PostalCodes []PostalCode `json:"postalCodes"`
	Version     int          `json:"version"`
}

// CityRequest defines model for CityRequest.
type CityRequest struct {
	Name        string          `json:"name"`
	PostalCodes []PostalCodeRef `json:"postalCodes"`
	Version     int             `json:"version"`
}

// Curriculum defines model for Curriculum.
type Curriculum struct {
	ActiveFrom  *time.Time `json:"activeFrom,omitempty"`
	ActiveSince *time.Time `json:"activeSince,omitempty"`
	ActiveUntil *time.Time `json:"activeUntil,omitempty"`
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Version     int        `json:"version"`
}

// EntityRef defines model for EntityRef.
type EntityRef struct {
	ID string `json:"id"`
}

// Exam defines model for Exam.
type Exam struct {
	ID          string       `json:"id"`
	SchoolClass *SchoolClass `json:"schoolClass,omitempty"`
	Version     int          `json:"version"`
}

// ExamRequest defines model for ExamRequest.
type ExamRequest struct {
	SchoolClass *EntityRef `json:"schoolClass,omitempty"`
	Version     int        `json:"version"`
}

// Grade defines model for Grade.
type Grade struct {
	Exam    *Exam    `json:"exam,omitempty"`
	Grade   *float64 `json:"grade,omitempty"`
	ID      string   `json:"id"`
	Student *Student `json:"student,omitempty"`
	Version int      `json:"version"`
}

// GradeRequest defines model for GradeRequest.
type GradeRequest struct {
	Exam    *EntityRef `json:"exam,omitempty"`
	Grade   *float64   `json:"grade,omitempty"`
	Student *EntityRef `json:"student,omitempty"`
	Version int        `json:"version"`
}

// Guardian defines model for Guardian.
type Guardian struct {
	Address     *Address   `json:"address,omitempty"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty"`
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Prename     string     `json:"prename"`
	Sub         *string    `json:"sub,omitempty"`
	Version     int        `json:"version"`
}

// GuardianRequest defines model for GuardianRequest.
type GuardianRequest struct {
	Address     *EntityRef `json:"address,omitempty"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty"`
	Name        string     `json:"name"`
	Prename     string     `json:"prename"`
	Sub         *string    `json:"sub,omitempty"`
	Version     int        `json:"version"`
}

// Lesson defines model for Lesson.
type Lesson struct {
	// DayOfWeek 1=Monday, 5=Friday
	DayOfWeek   *int         `json:"dayOfWeek,omitempty"`
	EndTime     *string      `json:"endTime,omitempty"`
	ID          string       `json:"id"`
	Period      *int         `json:"period,omitempty"`
	Room        *Room        `json:"room,omitempty"`
	SchoolClass *SchoolClass `json:"schoolClass,omitempty"`
	StartTime   *string      `json:"startTime,omitempty"`
	Subject     *Subject     `json:"subject,omitempty"`
	Teacher     *Teacher     `json:"teacher,omitempty"`
	Version     int          `json:"version"`
}

// LessonRequest defines model for LessonRequest.
type LessonRequest struct {
	DayOfWeek   *int       `json:"dayOfWeek,omitempty"`
	EndTime     *string    `json:"endTime,omitempty"`
	Period      *int       `json:"period,omitempty"`
	Room        *EntityRef `json:"room,omitempty"`
	SchoolClass *EntityRef `json:"schoolClass,omitempty"`
	StartTime   *string    `json:"startTime,omitempty"`
	Subject     *EntityRef `json:"subject,omitempty"`
	Teacher     *EntityRef `json:"teacher,omitempty"`
	Version     int        `json:"version"`
}

// Location defines model for Location.
type Location struct {
	ID      string   `json:"id"`
	Lat     *float64 `json:"lat,omitempty"`
	Lon     *float64 `json:"lon,omitempty"`
	Version int      `json:"version"`
}

// Person defines model for Person.
type Person struct {
	Address     *Address   `json:"address,omitempty"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty"`
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Prename     string     `json:"prename"`
	Sub         *string    `json:"sub,omitempty"`
	Version     int        `json:"version"`
}

// PersonRequest defines model for PersonRequest.
type PersonRequest struct {
	Address     *EntityRef `json:"address,omitempty"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty"`
	Name        string     `json:"name"`
	Prename     string     `json:"prename"`
	Sub         *string    `json:"sub,omitempty"`
	Version     int        `json:"version"`
}

// PostalCode defines model for PostalCode.
type PostalCode struct {
	City    string `json:"city"`
	ID      string `json:"id"`
	Number  int    `json:"number"`
	Version int    `json:"version"`
}

// PostalCodeRef defines model for PostalCodeRef.
type PostalCodeRef struct {
	ID string `json:"id"`
}

// Receipt defines model for Receipt.
type Receipt struct {
	AccountID      string         `json:"accountId"`
	FileID         string         `json:"fileId"`
	ID             string         `json:"id"`
	Items          []ReceiptItem  `json:"items"`
	ReceiptOwnerID string         `json:"receiptOwnerId"`
	Splits         []ReceiptSplit `json:"splits"`
	Status         ReceiptStatus  `json:"status"`
	Taxes          float64        `json:"taxes"`
	Time           time.Time      `json:"time"`
	TotalPrice     float64        `json:"totalPrice"`
}

// ReceiptItem defines model for ReceiptItem.
type ReceiptItem struct {
	Amount float64 `json:"amount"`
	Name   string  `json:"name"`
	Price  float64 `json:"price"`
}

// ReceiptSplit defines model for ReceiptSplit.
type ReceiptSplit struct {
	AccountID string  `json:"accountId"`
	Amount    float64 `json:"amount"`
	ClassID   string  `json:"classId"`
}

// ReceiptStatus defines model for ReceiptStatus.
type ReceiptStatus string

// Room defines model for Room.
type Room struct {
	Building *Building `json:"building,omitempty"`
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	RoomType *RoomType `json:"roomType,omitempty"`
	Version  int       `json:"version"`
}

// RoomRequest defines model for RoomRequest.
type RoomRequest struct {
	Building EntityRef `json:"building"`
	Name     string    `json:"name"`
	Version  int       `json:"version"`
}

// RoomType defines model for RoomType.
type RoomType string

// SchoolClass defines model for SchoolClass.
type SchoolClass struct {
	Classroom  *Room       `json:"classroom,omitempty"`
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	SchoolYear *SchoolYear `json:"schoolYear,omitempty"`
	Shortcut   string      `json:"shortcut"`
	Students   []Student   `json:"students"`
	Teachers   []Teacher   `json:"teachers"`
	Version    int         `json:"version"`
}

// SchoolClassRequest defines model for SchoolClassRequest.
type SchoolClassRequest struct {
	Classroom  *EntityRef   `json:"classroom,omitempty"`
	Name       *string      `json:"name,omitempty"`
	SchoolYear *EntityRef   `json:"schoolYear,omitempty"`
	Shortcut   *string      `json:"shortcut,omitempty"`
	Students   *[]EntityRef `json:"students,omitempty"`
	Teachers   *[]EntityRef `json:"teachers,omitempty"`
	Version    int          `json:"version"`
}

// SchoolYear defines model for SchoolYear.
type SchoolYear struct {
	From    *time.Time `json:"from,omitempty"`
	ID      string     `json:"id"`
	To      *time.Time `json:"to,omitempty"`
	Version int        `json:"version"`
}

// Student defines model for Student.
type Student struct {
	Address            *Address      `json:"address,omitempty"`
	CurrentSchoolClass *SchoolClass  `json:"currentSchoolClass,omitempty"`
	DateOfBirth        *time.Time    `json:"dateOfBirth,omitempty"`
	Grades             []Grade       `json:"grades"`
	Guardians          []Guardian    `json:"guardians"`
	ID                 string        `json:"id"`
	Name               string        `json:"name"`
	PastSchoolClasses  []SchoolClass `json:"pastSchoolClasses"`
	Prename            string        `json:"prename"`
	Sub                *string       `json:"sub,omitempty"`
	Version            int           `json:"version"`
}

// StudentRequest defines model for StudentRequest.
type StudentRequest struct {
	Address            *EntityRef   `json:"address,omitempty"`
	CurrentSchoolClass *EntityRef   `json:"currentSchoolClass,omitempty"`
	DateOfBirth        *time.Time   `json:"dateOfBirth,omitempty"`
	Guardians          []EntityRef  `json:"guardians"`
	Name               string       `json:"name"`
	PastSchoolClasses  *[]EntityRef `json:"pastSchoolClasses,omitempty"`
	Prename            string       `json:"prename"`
	Sub                *string      `json:"sub,omitempty"`
	Version            int          `json:"version"`
}

// Subject defines model for Subject.
type Subject struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Teachers []Teacher `json:"teachers"`
	Version  int       `json:"version"`
}

// SubjectRequest defines model for SubjectRequest.
type SubjectRequest struct {
	Name     *string      `json:"name,omitempty"`
	Teachers *[]EntityRef `json:"teachers,omitempty"`
	Version  int          `json:"version"`
}

// Teacher defines model for Teacher.
type Teacher struct {
	Address       *Address   `json:"address,omitempty"`
	AtSchoolSince time.Time  `json:"atSchoolSince"`
	AtSchoolUntil *time.Time `json:"atSchoolUntil,omitempty"`
	DateOfBirth   *time.Time `json:"dateOfBirth,omitempty"`
	Iban          *string    `json:"iban,omitempty"`
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	Prename       string     `json:"prename"`
	Sub           *string    `json:"sub,omitempty"`
	Version       int        `json:"version"`
}

// TeacherRequest defines model for TeacherRequest.
type TeacherRequest struct {
	Address       *EntityRef `json:"address,omitempty"`
	AtSchoolSince time.Time  `json:"atSchoolSince"`
	AtSchoolUntil *time.Time `json:"atSchoolUntil,omitempty"`
	DateOfBirth   *time.Time `json:"dateOfBirth,omitempty"`
	Iban          *string    `json:"iban,omitempty"`
	Name          string     `json:"name"`
	Prename       string     `json:"prename"`
	Sub           *string    `json:"sub,omitempty"`
	Version       int        `json:"version"`
}

// ListReceiptsParams defines parameters for ListReceipts.
type ListReceiptsParams struct {
	// Owner Filter by receiptOwnerId
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`
}

// CreateAddressJSONRequestBody defines body for CreateAddress for application/json ContentType.
type CreateAddressJSONRequestBody = AddressRequest

// UpdateAddressJSONRequestBody defines body for UpdateAddress for application/json ContentType.
type UpdateAddressJSONRequestBody = AddressRequest

// CreateBuildingJSONRequestBody defines body for CreateBuilding for application/json ContentType.
type CreateBuildingJSONRequestBody = BuildingRequest

// UpdateBuildingJSONRequestBody defines body for UpdateBuilding for application/json ContentType.
type UpdateBuildingJSONRequestBody = BuildingRequest

// CreateCityJSONRequestBody defines body for CreateCity for application/json ContentType.
type CreateCityJSONRequestBody = CityRequest

// UpdateCityJSONRequestBody defines body for UpdateCity for application/json ContentType.
type UpdateCityJSONRequestBody = CityRequest

// CreateCurriculumJSONRequestBody defines body for CreateCurriculum for application/json ContentType.
type CreateCurriculumJSONRequestBody = Curriculum

// UpdateCurriculumJSONRequestBody defines body for UpdateCurriculum for application/json ContentType.
type UpdateCurriculumJSONRequestBody = Curriculum

// CreateExamJSONRequestBody defines body for CreateExam for application/json ContentType.
type CreateExamJSONRequestBody = ExamRequest

// UpdateExamJSONRequestBody defines body for UpdateExam for application/json ContentType.
type UpdateExamJSONRequestBody = ExamRequest

// CreateGradeJSONRequestBody defines body for CreateGrade for application/json ContentType.
type CreateGradeJSONRequestBody = GradeRequest

// UpdateGradeJSONRequestBody defines body for UpdateGrade for application/json ContentType.
type UpdateGradeJSONRequestBody = GradeRequest

// CreateGuardianJSONRequestBody defines body for CreateGuardian for application/json ContentType.
type CreateGuardianJSONRequestBody = GuardianRequest

// UpdateGuardianJSONRequestBody defines body for UpdateGuardian for application/json ContentType.
type UpdateGuardianJSONRequestBody = GuardianRequest

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonRequest

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = Location

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = Location

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = PersonRequest

// UpdatePersonJSONRequestBody defines body for UpdatePerson for application/json ContentType.
type UpdatePersonJSONRequestBody = PersonRequest

// CreatePostalCodeJSONRequestBody defines body for CreatePostalCode for application/json ContentType.
type CreatePostalCodeJSONRequestBody = PostalCode

// UpdatePostalCodeJSONRequestBody defines body for UpdatePostalCode for application/json ContentType.
type UpdatePostalCodeJSONRequestBody = PostalCode

// CreateReceiptJSONRequestBody defines body for CreateReceipt for application/json ContentType.
type CreateReceiptJSONRequestBody = Receipt

// UpdateReceiptJSONRequestBody defines body for UpdateReceipt for application/json ContentType.
type UpdateReceiptJSONRequestBody = Receipt

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = RoomRequest

// UpdateRoomJSONRequestBody defines body for UpdateRoom for application/json ContentType.
type UpdateRoomJSONRequestBody = RoomRequest

// CreateSchoolClassJSONRequestBody defines body for CreateSchoolClass for application/json ContentType.
type CreateSchoolClassJSONRequestBody = SchoolClassRequest

// UpdateSchoolClassJSONRequestBody defines body for UpdateSchoolClass for application/json ContentType.
type UpdateSchoolClassJSONRequestBody = SchoolClassRequest

// CreateSchoolYearJSONRequestBody defines body for CreateSchoolYear for application/json ContentType.
type CreateSchoolYearJSONRequestBody = SchoolYear

// UpdateSchoolYearJSONRequestBody defines body for UpdateSchoolYear for application/json ContentType.
type UpdateSchoolYearJSONRequestBody = SchoolYear

// CreateStudentJSONRequestBody defines body for CreateStudent for application/json ContentType.
type CreateStudentJSONRequestBody = StudentRequest

// UpdateStudentJSONRequestBody defines body for UpdateStudent for application/json ContentType.
type UpdateStudentJSONRequestBody = StudentRequest

// CreateSubjectJSONRequestBody defines body for CreateSubject for application/json ContentType.
type CreateSubjectJSONRequestBody = SubjectRequest

// UpdateSubjectJSONRequestBody defines body for UpdateSubject for application/json ContentType.
type UpdateSubjectJSONRequestBody = SubjectRequest

// CreateTeacherJSONRequestBody defines body for CreateTeacher for application/json ContentType.
type CreateTeacherJSONRequestBody = TeacherRequest

// UpdateTeacherJSONRequestBody defines body for UpdateTeacher for application/json ContentType.
type UpdateTeacherJSONRequestBody = TeacherRequest
